# Name of your application. Used to uniquely configure containers.
service: kindly

# Name of the container image.
image: delonnewman/kindly

# Deploy to these servers.
servers:
  - 52.87.153.28

labels:
  org.opencontainers.image.source: "https://github.com/delonnewman/kindly"

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: delonnewman

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    DB_HOST: 172.30.4.204
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

# Use a different ssh user than root
ssh:
  user: admin

# Configure builder setup.
builder:
  args:
    RUBY_VERSION: 3.2.2
  local:
    arch: arm64
  remote:
    arch: amd64

accessories:
  db:
    image: postgres:15
    host: 18.234.129.38
    port: 5432
    env:
      clear:
        - POSTGRES_USER
        - POSTGRES_DB
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql
